services:
  next:
    build:
      context: .
      target: next
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev"]