name: CI/CD

run-name: ${{ github.actor }} is running CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["chrome", "edge"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: npm run build
          start: npm start
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress videos for ${{ matrix.browser }}
          path: cypress/videos

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls"